CREATE USER C##APP IDENTIFIED BY APP123;
GRANT CONNECT, RESOURCE TO C##APP;
ALTER USER C##APP quota unlimited on users;

CREATE USER C##AUDIT IDENTIFIED BY AUDIT123;
GRANT CONNECT, RESOURCE TO C##AUDIT;
ALTER USER C##AUDIT quota unlimited on users;