DROP TRIGGER TG_AUD_EVE;
DROP TRIGGER TG_AUD_JOG;
DROP TRIGGER TG_AUD_PAR;
DROP TRIGGER TG_AUD_EST;
DROP TRIGGER TG_AUD_CID;
DROP TRIGGER TG_AUD_ESC;
DROP TRIGGER TG_AUD_TRE;
DROP TRIGGER TG_AUD_SEL;
DROP TRIGGER TG_AUD_COP;

DROP PROCEDURE PR_HEVE;
DROP PROCEDURE PR_HJSC;
DROP PROCEDURE PR_HJOG;
DROP PROCEDURE PR_HPAR;
DROP PROCEDURE PR_HEST;
DROP PROCEDURE PR_HCID;
DROP PROCEDURE PR_HESC;
DROP PROCEDURE PR_HTRE;
DROP PROCEDURE PR_HSEL;
DROP PROCEDURE PR_HCOP;


DROP TRIGGER tg_bi_eve;
DROP TRIGGER tg_bi_jog;
DROP TRIGGER tg_bi_par;
DROP TRIGGER tg_bi_est;
DROP TRIGGER tg_bi_cid;
DROP TRIGGER tg_bi_esc;
DROP TRIGGER tg_bi_tre;
DROP TRIGGER tg_bi_sel;
DROP TRIGGER tg_bi_cop;

DROP SEQUENCE seq_eve;
DROP SEQUENCE seq_jog;
DROP SEQUENCE seq_par;
DROP SEQUENCE seq_est;
DROP SEQUENCE seq_cid;
DROP SEQUENCE seq_esc;
DROP SEQUENCE seq_tre;
DROP SEQUENCE seq_sel;
DROP SEQUENCE seq_cop;

DROP TABLE eventos;
DROP TABLE escalacoes_jogadores;
DROP TABLE jogadores;
DROP TABLE partidas;
DROP TABLE estadios;
DROP TABLE cidades;
DROP TABLE escalacoes;
DROP TABLE treinadores ;
DROP TABLE selecoes;
DROP TABLE copas;

DROP TABLE heventos;
DROP TABLE hescalacoes_jogadores;
DROP TABLE hjogadores;
DROP TABLE hpartidas;
DROP TABLE hestadios;
DROP TABLE hcidades;
DROP TABLE hescalacoes;
DROP TABLE htreinadores ;
DROP TABLE hselecoes;
DROP TABLE hcopas;
