INSERT INTO cidades VALUES (0, 'Belo Horizonte');
INSERT INTO cidades VALUES (0, 'Berlin');
INSERT INTO cidades VALUES (0, 'Bordeaux');
INSERT INTO cidades VALUES (0, 'Brasilia');
INSERT INTO cidades VALUES (0, 'Busan');
INSERT INTO cidades VALUES (0, 'Cape Town');
INSERT INTO cidades VALUES (0, 'Cologne');
INSERT INTO cidades VALUES (0, 'Cuiaba');
INSERT INTO cidades VALUES (0, 'Curitiba');
INSERT INTO cidades VALUES (0, 'Daegu');
INSERT INTO cidades VALUES (0, 'Daejeon');
INSERT INTO cidades VALUES (0, 'Dortmund');
INSERT INTO cidades VALUES (0, 'Durban');
INSERT INTO cidades VALUES (0, 'Fortaleza');
INSERT INTO cidades VALUES (0, 'Frankfurt/Main');
INSERT INTO cidades VALUES (0, 'Gelsenkirchen');
INSERT INTO cidades VALUES (0, 'Gwangju');
INSERT INTO cidades VALUES (0, 'Hamburg');
INSERT INTO cidades VALUES (0, 'Hanover');
INSERT INTO cidades VALUES (0, 'Ibaraki');
INSERT INTO cidades VALUES (0, 'Incheon');
INSERT INTO cidades VALUES (0, 'Jeju');
INSERT INTO cidades VALUES (0, 'Jeonju');
INSERT INTO cidades VALUES (0, 'Johannesburg');
INSERT INTO cidades VALUES (0, 'Kaiserslautern');
INSERT INTO cidades VALUES (0, 'Kobe');
INSERT INTO cidades VALUES (0, 'Leipzig');
INSERT INTO cidades VALUES (0, 'Lens');
INSERT INTO cidades VALUES (0, 'Lyon');
INSERT INTO cidades VALUES (0, 'Manaus');
INSERT INTO cidades VALUES (0, 'Mangaung/Bloemfontein');
INSERT INTO cidades VALUES (0, 'Marseilles');
INSERT INTO cidades VALUES (0, 'Montpellier');
INSERT INTO cidades VALUES (0, 'Munich');
INSERT INTO cidades VALUES (0, 'Nantes');
INSERT INTO cidades VALUES (0, 'Natal');
INSERT INTO cidades VALUES (0, 'Nelson Mandela Bay/Port Elizabeth');
INSERT INTO cidades VALUES (0, 'Nelspruit');
INSERT INTO cidades VALUES (0, 'Niigata');
INSERT INTO cidades VALUES (0, 'Nuremberg');
INSERT INTO cidades VALUES (0, 'Oita');
INSERT INTO cidades VALUES (0, 'Osaka');
INSERT INTO cidades VALUES (0, 'Paris');
INSERT INTO cidades VALUES (0, 'Phokeng');
INSERT INTO cidades VALUES (0, 'Polokwane');
INSERT INTO cidades VALUES (0, 'Porto Alegre');
INSERT INTO cidades VALUES (0, 'Recife');
INSERT INTO cidades VALUES (0, 'Rifu');
INSERT INTO cidades VALUES (0, 'Rio De Janeiro');
INSERT INTO cidades VALUES (0, 'Saint-Denis');
INSERT INTO cidades VALUES (0, 'Saint-Etienne');
INSERT INTO cidades VALUES (0, 'Saitama');
INSERT INTO cidades VALUES (0, 'Salvador');
INSERT INTO cidades VALUES (0, 'Sao Paulo');
INSERT INTO cidades VALUES (0, 'Sapporo');
INSERT INTO cidades VALUES (0, 'Seoul');
INSERT INTO cidades VALUES (0, 'Shizuoka');
INSERT INTO cidades VALUES (0, 'Stuttgart');
INSERT INTO cidades VALUES (0, 'Suwon');
INSERT INTO cidades VALUES (0, 'Toulouse');
INSERT INTO cidades VALUES (0, 'Tshwane/Pretoria');
INSERT INTO cidades VALUES (0, 'Ulsan');
INSERT INTO cidades VALUES (0, 'Yokohama');

insert into copas values (0, 1998);
insert into copas values (0, 2002);
insert into copas values (0, 2006);
insert into copas values (0, 2010);
insert into copas values (0, 2014);

INSERT INTO selecoes VALUES (0, 'Algeria','ALG');
INSERT INTO selecoes VALUES (0, 'Angola','ANG');
INSERT INTO selecoes VALUES (0, 'Argentina','ARG');
INSERT INTO selecoes VALUES (0, 'Australia','AUS');
INSERT INTO selecoes VALUES (0, 'Austria','AUT');
INSERT INTO selecoes VALUES (0, 'Belgium','BEL');
INSERT INTO selecoes VALUES (0, 'Bosnia and Herzegovina','BIH');
INSERT INTO selecoes VALUES (0, 'Brazil','BRA');
INSERT INTO selecoes VALUES (0, 'Bulgaria','BUL');
INSERT INTO selecoes VALUES (0, 'Cameroon','CMR');
INSERT INTO selecoes VALUES (0, 'Chile','CHI');
INSERT INTO selecoes VALUES (0, 'China PR','CHN');
INSERT INTO selecoes VALUES (0, 'Colombia','COL');
INSERT INTO selecoes VALUES (0, 'Costa Rica','CRC');
INSERT INTO selecoes VALUES (0, 'Cote d''Ivoire','CIV');
INSERT INTO selecoes VALUES (0, 'Croatia','CRO');
INSERT INTO selecoes VALUES (0, 'Czech Republic','CZE');
INSERT INTO selecoes VALUES (0, 'Denmark','DEN');
INSERT INTO selecoes VALUES (0, 'Ecuador','ECU');
INSERT INTO selecoes VALUES (0, 'England','ENG');
INSERT INTO selecoes VALUES (0, 'France','FRA');
INSERT INTO selecoes VALUES (0, 'Germany','GER');
INSERT INTO selecoes VALUES (0, 'Ghana','GHA');
INSERT INTO selecoes VALUES (0, 'Greece','GRE');
INSERT INTO selecoes VALUES (0, 'Honduras','HON');
INSERT INTO selecoes VALUES (0, 'IR Iran','IRN');
INSERT INTO selecoes VALUES (0, 'Iran','IRN');
INSERT INTO selecoes VALUES (0, 'Italy','ITA');
INSERT INTO selecoes VALUES (0, 'Jamaica','JAM');
INSERT INTO selecoes VALUES (0, 'Japan','JPN');
INSERT INTO selecoes VALUES (0, 'Korea DPR','PRK');
INSERT INTO selecoes VALUES (0, 'Korea Republic','KOR');
INSERT INTO selecoes VALUES (0, 'Mexico','MEX');
INSERT INTO selecoes VALUES (0, 'Morocco','MAR');
INSERT INTO selecoes VALUES (0, 'Netherlands','NED');
INSERT INTO selecoes VALUES (0, 'New Zealand','NZL');
INSERT INTO selecoes VALUES (0, 'Nigeria','NGA');
INSERT INTO selecoes VALUES (0, 'Norway','NOR');
INSERT INTO selecoes VALUES (0, 'Paraguay','PAR');
INSERT INTO selecoes VALUES (0, 'Poland','POL');
INSERT INTO selecoes VALUES (0, 'Portugal','POR');
INSERT INTO selecoes VALUES (0, 'Republic of Ireland','IRL');
INSERT INTO selecoes VALUES (0, 'Romania','ROU');
INSERT INTO selecoes VALUES (0, 'Russia','RUS');
INSERT INTO selecoes VALUES (0, 'Saudi Arabia','KSA');
INSERT INTO selecoes VALUES (0, 'Scotland','SCO');
INSERT INTO selecoes VALUES (0, 'Senegal','SEN');
INSERT INTO selecoes VALUES (0, 'Serbia','SRB');
INSERT INTO selecoes VALUES (0, 'Serbia and Montenegro','SCG');
INSERT INTO selecoes VALUES (0, 'Slovakia','SVK');
INSERT INTO selecoes VALUES (0, 'Slovenia','SVN');
INSERT INTO selecoes VALUES (0, 'South Africa','RSA');
INSERT INTO selecoes VALUES (0, 'Spain','ESP');
INSERT INTO selecoes VALUES (0, 'Sweden','SWE');
INSERT INTO selecoes VALUES (0, 'Switzerland','SUI');
INSERT INTO selecoes VALUES (0, 'Togo','TOG');
INSERT INTO selecoes VALUES (0, 'Trinidad and Tobago','TRI');
INSERT INTO selecoes VALUES (0, 'Tunisia','TUN');
INSERT INTO selecoes VALUES (0, 'Turkey','TUR');
INSERT INTO selecoes VALUES (0, 'Ukraine','UKR');
INSERT INTO selecoes VALUES (0, 'Uruguay','URU');
INSERT INTO selecoes VALUES (0, 'USA','USA');
INSERT INTO selecoes VALUES (0, 'Yugoslavia','YUG');

update tabelao set tab_cid_nome = (select cid_id from cidades where cid_nome = tabelao.tab_cid_nome);
update tabelao set tab_sel_iniciais_time_b = (select sel_id from selecoes where sel_trigrama = tabelao.tab_sel_iniciais_time_b);

select count (tab_cop_edicao) from tabelao;
select * from tabelao where tab_nome_time_a = 'Brazil' or tab_nome_time_b = 'Brazil';